services:
  app:
    build: .
    image: ghcr.io/johan198205/dashboard-mittriks:local
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped


